# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ImagenesPaquetes/*.sln .
COPY ImagenesPaquetes/ImagenesPaquetes.API/*.csproj ./ImagenesPaquetes.API/
COPY ImagenesPaquetes/ImagenesPaquetes.Application/*.csproj ./ImagenesPaquetes.Application/
COPY ImagenesPaquetes/ImagenesPaquetes.Domain/*.csproj ./ImagenesPaquetes.Domain/
COPY ImagenesPaquetes/ImagenesPaquetes.Infrastructure/*.csproj ./ImagenesPaquetes.Infrastructure/

RUN dotnet restore

COPY . .
RUN dotnet publish ImagenesPaquetes/ImagenesPaquetes.API -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "ImagenesPaquetes.API.dll"]
